from __future__ import annotations

from enum import IntEnum
from typing import Any, ClassVar, TypeAlias

from .system import Angle, Time, Vector3, Vector3Like

BytesLike: TypeAlias = bytes | bytearray | memoryview


def __getattr__(name: str) -> Any: ...


class PlaybackDevice:
    @staticmethod
    def get_available_devices() -> list[str]: ...
    @staticmethod
    def get_default_device() -> str | None: ...
    @staticmethod
    def set_device(name: str) -> bool: ...
    @staticmethod
    def get_device() -> str | None: ...


class Listener:
    @staticmethod
    def set_global_volume(volume: float) -> None: ...
    @staticmethod
    def get_global_volume() -> float: ...
    @staticmethod
    def set_position(position: Vector3Like) -> None: ...
    @staticmethod
    def get_position() -> Vector3: ...
    @staticmethod
    def set_direction(direction: Vector3Like) -> None: ...
    @staticmethod
    def get_direction() -> Vector3: ...
    @staticmethod
    def set_velocity(velocity: Vector3Like) -> None: ...
    @staticmethod
    def get_velocity() -> Vector3: ...
    @staticmethod
    def set_up_vector(up_vector: Vector3Like) -> None: ...
    @staticmethod
    def get_up_vector() -> Vector3: ...
    @staticmethod
    def set_cone(cone: Cone) -> None: ...
    @staticmethod
    def get_cone() -> Cone: ...


class Cone:
    def __init__(
        self,
        inner_angle: Angle | None = None,
        outer_angle: Angle | None = None,
        outer_gain: float = 1.0,
    ) -> None: ...
    @property
    def inner_angle(self) -> Angle: ...
    @inner_angle.setter
    def inner_angle(self, angle: Angle) -> None: ...
    @property
    def outer_angle(self) -> Angle: ...
    @outer_angle.setter
    def outer_angle(self, angle: Angle) -> None: ...
    @property
    def outer_gain(self) -> float: ...
    @outer_gain.setter
    def outer_gain(self, outer_gain: float) -> None: ...


class SoundChannel(IntEnum):
    UNSPECIFIED = 0
    MONO = 1
    FRONT_LEFT = 2
    FRONT_RIGHT = 3
    FRONT_CENTER = 4
    FRONT_LEFT_OF_CENTER = 5
    FRONT_RIGHT_OF_CENTER = 6
    LOW_FREQUENCY_EFFECTS = 7
    BACK_LEFT = 8
    BACK_RIGHT = 9
    BACK_CENTER = 10
    SIDE_LEFT = 11
    SIDE_RIGHT = 12
    TOP_CENTER = 13
    TOP_FRONT_LEFT = 14
    TOP_FRONT_RIGHT = 15
    TOP_FRONT_CENTER = 16
    TOP_BACK_LEFT = 17
    TOP_BACK_RIGHT = 18
    TOP_BACK_CENTER = 19


class Chunk:
    def __init__(self, data: bytes | bytearray | memoryview) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, sample: int) -> None: ...
    @property
    def data(self) -> bytes: ...


class SoundBuffer:
    def __init__(self) -> None: ...
    @classmethod
    def from_file(cls, filename: str) -> SoundBuffer: ...
    @classmethod
    def from_memory(cls, data: BytesLike) -> SoundBuffer: ...
    @classmethod
    def from_samples(
        cls,
        samples: Chunk,
        channel_count: int,
        sample_rate: int,
        channel_map: list[SoundChannel] | tuple[SoundChannel, ...] | None = None,
    ) -> SoundBuffer: ...
    def to_file(self, filename: str) -> None: ...
    @property
    def samples(self) -> Chunk: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def channel_map(self) -> list[SoundChannel]: ...
    @property
    def duration(self) -> Time: ...
    def __getattr__(self, name: str) -> Any: ...


class Status(IntEnum):
    STOPPED = 0
    PAUSED = 1
    PLAYING = 2


class SoundSource:
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, pitch: float) -> None: ...
    @property
    def pan(self) -> float: ...
    @pan.setter
    def pan(self, pan: float) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, volume: float) -> None: ...
    @property
    def spatialization_enabled(self) -> bool: ...
    @spatialization_enabled.setter
    def spatialization_enabled(self, enabled: bool) -> None: ...
    @property
    def position(self) -> Vector3: ...
    @position.setter
    def position(self, position: Vector3Like) -> None: ...
    @property
    def direction(self) -> Vector3: ...
    @direction.setter
    def direction(self, direction: Vector3Like) -> None: ...
    @property
    def cone(self) -> Cone: ...
    @cone.setter
    def cone(self, cone: Cone) -> None: ...
    @property
    def velocity(self) -> Vector3: ...
    @velocity.setter
    def velocity(self, velocity: Vector3Like) -> None: ...
    @property
    def doppler_factor(self) -> float: ...
    @doppler_factor.setter
    def doppler_factor(self, factor: float) -> None: ...
    @property
    def directional_attenuation_factor(self) -> float: ...
    @directional_attenuation_factor.setter
    def directional_attenuation_factor(self, factor: float) -> None: ...
    @property
    def relative_to_listener(self) -> bool: ...
    @relative_to_listener.setter
    def relative_to_listener(self, relative_to_listener: bool) -> None: ...
    @property
    def min_distance(self) -> float: ...
    @min_distance.setter
    def min_distance(self, min_distance: float) -> None: ...
    @property
    def max_distance(self) -> float: ...
    @max_distance.setter
    def max_distance(self, max_distance: float) -> None: ...
    @property
    def min_gain(self) -> float: ...
    @min_gain.setter
    def min_gain(self, min_gain: float) -> None: ...
    @property
    def max_gain(self) -> float: ...
    @max_gain.setter
    def max_gain(self, max_gain: float) -> None: ...
    @property
    def attenuation(self) -> float: ...
    @attenuation.setter
    def attenuation(self, attenuation: float) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class Sound(SoundSource):
    def __init__(self, buffer: SoundBuffer | None = None) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def buffer(self) -> SoundBuffer: ...
    @buffer.setter
    def buffer(self, buffer: SoundBuffer) -> None: ...
    @property
    def loop(self) -> bool: ...
    @loop.setter
    def loop(self, loop: bool) -> None: ...
    @property
    def playing_offset(self) -> Time: ...
    @playing_offset.setter
    def playing_offset(self, playing_offset: Time) -> None: ...
    @property
    def status(self) -> Status: ...


class SoundStream(SoundSource):
    def __init__(self) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def initialize(
        self,
        channel_count: int,
        sample_rate: int,
        channel_map: list[SoundChannel] | tuple[SoundChannel, ...] | None = None,
    ) -> None: ...
    def on_get_data(self, chunk: Chunk) -> bool: ...
    def on_seek(self, time_offset: Time) -> None: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channel_map(self) -> list[SoundChannel]: ...
    @property
    def status(self) -> Status: ...
    @property
    def playing_offset(self) -> Time: ...
    @playing_offset.setter
    def playing_offset(self, playing_offset: Time) -> None: ...
    @property
    def loop(self) -> bool: ...
    @loop.setter
    def loop(self, loop: bool) -> None: ...


class Music(SoundStream):
    @classmethod
    def from_file(cls, filename: str) -> Music: ...
    @classmethod
    def from_memory(cls, data: BytesLike) -> Music: ...
    @property
    def duration(self) -> Time: ...
    @property
    def loop_points(self) -> tuple[Time, Time]: ...
    @loop_points.setter
    def loop_points(self, loop_points: tuple[Time, Time]) -> None: ...


class SoundRecorder:
    @staticmethod
    def is_available() -> bool: ...
    @staticmethod
    def get_available_devices() -> list[str]: ...
    @staticmethod
    def get_default_device() -> str | None: ...
    def start(self, sample_rate: int = 44100) -> bool: ...
    def stop(self) -> None: ...
    def set_device(self, name: str) -> bool: ...
    def get_device(self) -> str | None: ...
    def on_start(self) -> bool: ...
    def on_process_samples(self, chunk: Chunk) -> bool: ...
    def on_stop(self) -> None: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channel_count(self) -> int: ...
    @channel_count.setter
    def channel_count(self, channel_count: int) -> None: ...
    @property
    def channel_map(self) -> list[SoundChannel]: ...
    def __getattr__(self, name: str) -> Any: ...


class SoundBufferRecorder(SoundRecorder):
    def __init__(self) -> None: ...
    @property
    def buffer(self) -> SoundBuffer: ...
