from __future__ import annotations

from enum import IntEnum
from typing import Any, ClassVar

from .system import Time, Vector3, Vector3Like


def __getattr__(name: str) -> Any: ...


class Listener:
    @staticmethod
    def set_global_volume(volume: float) -> None: ...
    @staticmethod
    def get_global_volume() -> float: ...
    @staticmethod
    def set_position(position: Vector3Like) -> None: ...
    @staticmethod
    def get_position() -> Vector3: ...
    @staticmethod
    def set_direction(direction: Vector3Like) -> None: ...
    @staticmethod
    def get_direction() -> Vector3: ...
    @staticmethod
    def set_up_vector(up_vector: Vector3Like) -> None: ...
    @staticmethod
    def get_up_vector() -> Vector3: ...


class Chunk:
    def __init__(self, data: bytes | bytearray | memoryview) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, sample: int) -> None: ...
    @property
    def data(self) -> bytes: ...


class SoundBuffer:
    def __init__(self) -> None: ...
    @classmethod
    def from_file(cls, filename: str) -> SoundBuffer: ...
    @classmethod
    def from_memory(cls, data: bytes) -> SoundBuffer: ...
    @classmethod
    def from_samples(
        cls,
        samples: Chunk,
        channel_count: int,
        sample_rate: int,
    ) -> SoundBuffer: ...
    def to_file(self, filename: str) -> None: ...
    @property
    def samples(self) -> Chunk: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def duration(self) -> Time: ...
    def __getattr__(self, name: str) -> Any: ...


class Status(IntEnum):
    STOPPED = 0
    PAUSED = 1
    PLAYING = 2


class SoundSource:
    @property
    def pitch(self) -> float: ...
    @pitch.setter
    def pitch(self, pitch: float) -> None: ...
    @property
    def volume(self) -> float: ...
    @volume.setter
    def volume(self, volume: float) -> None: ...
    @property
    def position(self) -> Vector3: ...
    @position.setter
    def position(self, position: Vector3Like) -> None: ...
    @property
    def relative_to_listener(self) -> bool: ...
    @relative_to_listener.setter
    def relative_to_listener(self, relative_to_listener: bool) -> None: ...
    @property
    def min_distance(self) -> float: ...
    @min_distance.setter
    def min_distance(self, min_distance: float) -> None: ...
    @property
    def attenuation(self) -> float: ...
    @attenuation.setter
    def attenuation(self, attenuation: float) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class Sound(SoundSource):
    def __init__(self, buffer: SoundBuffer | None = None) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    @property
    def buffer(self) -> SoundBuffer: ...
    @buffer.setter
    def buffer(self, buffer: SoundBuffer) -> None: ...
    @property
    def loop(self) -> bool: ...
    @loop.setter
    def loop(self, loop: bool) -> None: ...
    @property
    def playing_offset(self) -> Time: ...
    @playing_offset.setter
    def playing_offset(self, playing_offset: Time) -> None: ...
    @property
    def status(self) -> Status: ...


class SoundStream(SoundSource):
    def __init__(self) -> None: ...
    def play(self) -> None: ...
    def pause(self) -> None: ...
    def stop(self) -> None: ...
    def initialize(self, channel_count: int, sample_rate: int) -> None: ...
    def on_get_data(self, chunk: Chunk) -> bool: ...
    def on_seek(self, time_offset: Time) -> None: ...
    @property
    def channel_count(self) -> int: ...
    @property
    def sample_rate(self) -> int: ...
    @property
    def status(self) -> Status: ...
    @property
    def playing_offset(self) -> Time: ...
    @playing_offset.setter
    def playing_offset(self, playing_offset: Time) -> None: ...
    @property
    def loop(self) -> bool: ...
    @loop.setter
    def loop(self, loop: bool) -> None: ...


class Music(SoundStream):
    @classmethod
    def from_file(cls, filename: str) -> Music: ...
    @classmethod
    def from_memory(cls, data: bytes) -> Music: ...
    @property
    def duration(self) -> Time: ...


class SoundRecorder:
    @staticmethod
    def is_available() -> bool: ...
    @staticmethod
    def get_available_devices() -> list[bytes]: ...
    @staticmethod
    def get_default_device() -> bytes: ...
    def start(self, sample_rate: int = 44100) -> bool: ...
    def stop(self) -> None: ...
    def set_device(self, name: bytes) -> bool: ...
    def get_device(self) -> bytes: ...
    def on_start(self) -> bool: ...
    def on_process_samples(self, chunk: Chunk) -> bool: ...
    def on_stop(self) -> None: ...
    @property
    def sample_rate(self) -> int: ...
    def __getattr__(self, name: str) -> Any: ...


class SoundBufferRecorder(SoundRecorder):
    def __init__(self) -> None: ...
    @property
    def buffer(self) -> SoundBuffer: ...
