from __future__ import annotations

from collections.abc import Iterator
from enum import IntEnum
from typing import Any, ClassVar, NoReturn

from .system import Vector2, Vector2Like
from .window import ContextSettings, VideoMode, Window

RectLike = Rect | tuple[int | float, int | float, int | float, int | float]


def __getattr__(name: str) -> Any: ...


class PrimitiveType:
    POINTS: ClassVar[int]
    LINES: ClassVar[int]
    LINES_STRIP: ClassVar[int]
    TRIANGLES: ClassVar[int]
    TRIANGLES_STRIP: ClassVar[int]
    TRIANGLES_FAN: ClassVar[int]
    QUADS: ClassVar[int]


class Rect:
    def __init__(self, position: Vector2Like = (0, 0), size: Vector2Like = (0, 0)) -> None: ...
    @property
    def left(self) -> int | float: ...
    @left.setter
    def left(self, left: int | float) -> None: ...
    @property
    def top(self) -> int | float: ...
    @top.setter
    def top(self, top: int | float) -> None: ...
    @property
    def width(self) -> int | float: ...
    @width.setter
    def width(self, width: int | float) -> None: ...
    @property
    def height(self) -> int | float: ...
    @height.setter
    def height(self, height: int | float) -> None: ...
    def __iter__(self) -> Iterator[int | float]: ...
    def contains(self, point: Vector2Like) -> bool: ...
    def intersects(self, rectangle: RectLike) -> Rect: ...


class Color:
    BLACK: ClassVar[Color]
    WHITE: ClassVar[Color]
    RED: ClassVar[Color]
    GREEN: ClassVar[Color]
    BLUE: ClassVar[Color]
    YELLOW: ClassVar[Color]
    MAGENTA: ClassVar[Color]
    CYAN: ClassVar[Color]
    TRANSPARENT: ClassVar[Color]

    def __init__(self, r: int = 0, g: int = 0, b: int = 0, a: int = 255) -> None: ...
    @property
    def r(self) -> int: ...
    @r.setter
    def r(self, r: int) -> None: ...
    @property
    def g(self) -> int: ...
    @g.setter
    def g(self, g: int) -> None: ...
    @property
    def b(self) -> int: ...
    @b.setter
    def b(self, b: int) -> None: ...
    @property
    def a(self) -> int: ...
    @a.setter
    def a(self, a: int) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
    def __add__(self, other: Color) -> Color: ...
    def __mul__(self, other: Color) -> Color: ...


class Transform:
    IDENTITY: ClassVar[Transform]

    def __init__(self) -> None: ...
    @classmethod
    def from_values(
        cls,
        a00: float,
        a01: float,
        a02: float,
        a10: float,
        a11: float,
        a12: float,
        a20: float,
        a21: float,
        a22: float,
    ) -> Transform: ...
    @property
    def matrix(self) -> int: ...
    @property
    def inverse(self) -> Transform: ...
    def transform_point(self, point: Vector2Like) -> Vector2: ...
    def transform_rectangle(self, rectangle: RectLike) -> Rect: ...
    def combine(self, transform: Transform) -> Transform: ...
    def translate(self, offset: Vector2Like) -> Transform: ...
    def rotate(self, angle: float, center: Vector2Like | None = None) -> Transform: ...
    def scale(self, factor: Vector2Like, center: Vector2Like | None = None) -> Transform: ...


class Factor(IntEnum):
    ZERO = 0


class Equation(IntEnum):
    ADD = 0
    SUBTRACT = 1


class BlendMode:
    def __init__(
        self,
        color_source_factor: int = ...,
        color_destination_factor: int = ...,
        color_blend_equation: int = ...,
        alpha_source_factor: int = ...,
        alpha_destination_factor: int = ...,
        alpha_blend_equation: int = ...,
    ) -> None: ...
    @property
    def color_src_factor(self) -> int: ...
    @property
    def color_dst_factor(self) -> int: ...
    @property
    def color_equation(self) -> int: ...
    @property
    def alpha_src_factor(self) -> int: ...
    @property
    def alpha_dst_factor(self) -> int: ...
    @property
    def alpha_equation(self) -> int: ...


BLEND_ALPHA: BlendMode
BLEND_ADD: BlendMode
BLEND_MULTIPLY: BlendMode
BLEND_NONE: BlendMode


class Image:
    @classmethod
    def create(cls, width: int, height: int, color: Color | None = None) -> Image: ...
    @classmethod
    def from_size(cls, width: int, height: int, color: Color | None = None) -> Image: ...
    @classmethod
    def from_pixels(cls, width: int, height: int, pixels: bytes | bytearray | memoryview) -> Image: ...
    @classmethod
    def from_file(cls, filename: str) -> Image: ...
    @classmethod
    def from_memory(cls, data: bytes) -> Image: ...
    def to_file(self, filename: str) -> None: ...
    @property
    def size(self) -> Vector2: ...
    @property
    def width(self) -> int | float: ...
    @property
    def height(self) -> int | float: ...
    @property
    def pixels(self) -> memoryview: ...
    def create_mask_from_color(self, color: Color, alpha: int = 0) -> None: ...
    def blit(
        self,
        source: Image,
        dest: Vector2Like,
        source_rect: RectLike | None = None,
        apply_alpha: bool = False,
    ) -> None: ...
    def flip_horizontally(self) -> None: ...
    def flip_vertically(self) -> None: ...
    def __getitem__(self, position: tuple[int, int]) -> Color: ...
    def __setitem__(self, position: tuple[int, int], color: Color) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class CoordinateType(IntEnum):
    NORMALIZED = 0
    PIXELS = 1


class Texture:
    @classmethod
    def create(cls, width: int, height: int) -> Texture: ...
    @classmethod
    def from_size(cls, width: int, height: int) -> Texture: ...
    @classmethod
    def from_file(cls, filename: str, area: RectLike | None = None) -> Texture: ...
    @classmethod
    def from_memory(cls, data: bytes, area: RectLike | None = None) -> Texture: ...
    @classmethod
    def from_image(cls, image: Image, area: RectLike | None = None) -> Texture: ...
    @property
    def size(self) -> Vector2: ...
    @property
    def width(self) -> int | float: ...
    @property
    def height(self) -> int | float: ...
    def copy_to_image(self) -> Image: ...
    def to_image(self) -> Image: ...
    def update(self, *args: Any, **kwargs: Any) -> None: ...
    def update_from_pixels(self, pixels: bytes | bytearray | memoryview, *args: int) -> None: ...
    def update_from_image(self, image: Image, position: Vector2Like | None = None) -> None: ...
    def update_from_window(self, window: Window, position: Vector2Like | None = None) -> None: ...
    @staticmethod
    def bind(texture: Texture | None = None, coordinate_type: int = ...) -> None: ...
    @property
    def smooth(self) -> bool: ...
    @smooth.setter
    def smooth(self, smooth: bool) -> None: ...
    @property
    def repeated(self) -> bool: ...
    @repeated.setter
    def repeated(self, repeated: bool) -> None: ...
    @property
    def native_handle(self) -> int: ...
    @staticmethod
    def get_maximum_size() -> int: ...
    def __getattr__(self, name: str) -> Any: ...


class Glyph:
    @property
    def advance(self) -> int | float: ...
    @advance.setter
    def advance(self, advance: int | float) -> None: ...
    @property
    def bounds(self) -> Rect: ...
    @bounds.setter
    def bounds(self, bounds: RectLike) -> None: ...
    @property
    def texture_rectangle(self) -> Rect: ...
    @texture_rectangle.setter
    def texture_rectangle(self, texture_rectangle: RectLike) -> None: ...


class Font:
    @classmethod
    def from_file(cls, filename: str) -> Font: ...
    @classmethod
    def from_memory(cls, data: bytes) -> Font: ...
    def get_glyph(self, code_point: int, character_size: int, bold: bool) -> Glyph: ...
    def get_kerning(self, first: int, second: int, character_size: int) -> float: ...
    def get_line_spacing(self, character_size: int) -> float: ...
    def get_texture(self, character_size: int) -> Texture: ...
    @property
    def info(self) -> bytes: ...


class Shader:
    @classmethod
    def from_file(
        cls,
        vertex: str | None = None,
        fragment: str | None = None,
    ) -> Shader: ...
    @classmethod
    def from_memory(
        cls,
        vertex: bytes | None = None,
        fragment: bytes | None = None,
    ) -> Shader: ...
    def set_parameter(self, *args: Any, **kwargs: Any) -> None: ...
    @staticmethod
    def bind(shader: Shader | None = None) -> None: ...
    @staticmethod
    def is_available() -> bool: ...
    def __getattr__(self, name: str) -> Any: ...


class RenderStates:
    DEFAULT: ClassVar[RenderStates]

    def __init__(
        self,
        blendmode: BlendMode = ...,
        transform: Transform | None = None,
        texture: Texture | None = None,
        shader: Shader | None = None,
    ) -> None: ...
    @property
    def blendmode(self) -> BlendMode: ...
    @blendmode.setter
    def blendmode(self, blendmode: BlendMode) -> None: ...
    @property
    def transform(self) -> Transform: ...
    @transform.setter
    def transform(self, transform: Transform) -> None: ...
    @property
    def texture(self) -> Texture | None: ...
    @texture.setter
    def texture(self, texture: Texture) -> None: ...
    @property
    def shader(self) -> Shader | None: ...
    @shader.setter
    def shader(self, shader: Shader) -> None: ...


class Drawable:
    def draw(self, target: RenderTarget, states: RenderStates) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class Transformable:
    @property
    def position(self) -> Vector2: ...
    @position.setter
    def position(self, position: Vector2Like) -> None: ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, angle: float) -> None: ...
    @property
    def ratio(self) -> Vector2: ...
    @ratio.setter
    def ratio(self, factor: Vector2Like) -> None: ...
    @property
    def origin(self) -> Vector2: ...
    @origin.setter
    def origin(self, origin: Vector2Like) -> None: ...
    def move(self, offset: Vector2Like) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def scale(self, factor: Vector2Like) -> None: ...
    @property
    def transform(self) -> Transform: ...
    @property
    def inverse_transform(self) -> Transform: ...
    def __getattr__(self, name: str) -> Any: ...


class TransformableDrawable(Drawable, Transformable):
    @property
    def transformable(self) -> Transformable: ...


class Sprite(TransformableDrawable):
    def __init__(self, texture: Texture, rectangle: RectLike | None = None) -> None: ...
    @property
    def texture(self) -> Texture: ...
    @texture.setter
    def texture(self, texture: Texture) -> None: ...
    @property
    def texture_rectangle(self) -> Rect: ...
    @texture_rectangle.setter
    def texture_rectangle(self, rectangle: RectLike) -> None: ...
    @property
    def color(self) -> Color: ...
    @color.setter
    def color(self, color: Color) -> None: ...
    @property
    def local_bounds(self) -> Rect: ...
    @property
    def global_bounds(self) -> Rect: ...


class Style(IntEnum):
    REGULAR = 0
    BOLD = 1
    ITALIC = 2
    UNDERLINED = 4
    STRIKE_THROUGH = 8


class Text(TransformableDrawable):
    def __init__(self, string: str | None = None, font: Font | None = None, character_size: int = 30) -> None: ...
    @property
    def string(self) -> str: ...
    @string.setter
    def string(self, string: str) -> None: ...
    @property
    def font(self) -> Font: ...
    @font.setter
    def font(self, font: Font) -> None: ...
    @property
    def character_size(self) -> int: ...
    @character_size.setter
    def character_size(self, size: int) -> None: ...
    @property
    def style(self) -> int: ...
    @style.setter
    def style(self, style: int) -> None: ...
    @property
    def color(self) -> Color: ...
    @color.setter
    def color(self, color: Color) -> None: ...
    @property
    def local_bounds(self) -> Rect: ...
    @property
    def global_bounds(self) -> Rect: ...
    def find_character_pos(self, index: int) -> Vector2: ...


class Shape(TransformableDrawable):
    @property
    def texture(self) -> Texture | None: ...
    @texture.setter
    def texture(self, texture: Texture | None) -> None: ...
    @property
    def texture_rectangle(self) -> Rect: ...
    @texture_rectangle.setter
    def texture_rectangle(self, rectangle: RectLike) -> None: ...
    @property
    def fill_color(self) -> Color: ...
    @fill_color.setter
    def fill_color(self, color: Color) -> None: ...
    @property
    def outline_color(self) -> Color: ...
    @outline_color.setter
    def outline_color(self, color: Color) -> None: ...
    @property
    def outline_thickness(self) -> float: ...
    @outline_thickness.setter
    def outline_thickness(self, thickness: float) -> None: ...
    @property
    def local_bounds(self) -> Rect: ...
    @property
    def global_bounds(self) -> Rect: ...
    @property
    def point_count(self) -> int: ...
    def get_point(self, index: int) -> Vector2: ...


class CircleShape(Shape):
    def __init__(self, radius: float = 0, point_count: int = 30) -> None: ...
    @property
    def radius(self) -> float: ...
    @radius.setter
    def radius(self, radius: float) -> None: ...
    @property
    def point_count(self) -> int: ...
    @point_count.setter
    def point_count(self, count: int) -> None: ...


class ConvexShape(Shape):
    def __init__(self, point_count: int = 0) -> None: ...
    @property
    def point_count(self) -> int: ...
    @point_count.setter
    def point_count(self, count: int) -> None: ...
    def set_point(self, index: int, point: Vector2Like) -> None: ...


class RectangleShape(Shape):
    def __init__(self, size: Vector2Like = (0, 0)) -> None: ...
    @property
    def size(self) -> Vector2: ...
    @size.setter
    def size(self, size: Vector2Like) -> None: ...


class Vertex:
    def __init__(
        self,
        position: Vector2Like | None = None,
        color: Color | None = None,
        tex_coords: Vector2Like | None = None,
    ) -> None: ...
    @property
    def position(self) -> Vector2: ...
    @position.setter
    def position(self, position: Vector2Like) -> None: ...
    @property
    def color(self) -> Color: ...
    @color.setter
    def color(self, color: Color) -> None: ...
    @property
    def tex_coords(self) -> Vector2: ...
    @tex_coords.setter
    def tex_coords(self, tex_coords: Vector2Like) -> None: ...


class VertexArray(Drawable):
    def __init__(self, type: int = ..., vertex_count: int = 0) -> None: ...
    def __len__(self) -> int: ...
    def __getitem__(self, index: int) -> Vertex: ...
    def __setitem__(self, index: int, vertex: Vertex) -> None: ...
    def clear(self) -> None: ...
    def resize(self, vertex_count: int) -> None: ...
    def append(self, vertex: Vertex) -> None: ...
    @property
    def primitive_type(self) -> int: ...
    @primitive_type.setter
    def primitive_type(self, primitive_type: int) -> None: ...
    @property
    def bounds(self) -> Rect: ...


class View:
    def __init__(self, rectangle: RectLike | None = None) -> None: ...
    @property
    def center(self) -> Vector2: ...
    @center.setter
    def center(self, center: Vector2Like) -> None: ...
    @property
    def size(self) -> Vector2: ...
    @size.setter
    def size(self, size: Vector2Like) -> None: ...
    @property
    def rotation(self) -> float: ...
    @rotation.setter
    def rotation(self, angle: float) -> None: ...
    @property
    def viewport(self) -> Rect: ...
    @viewport.setter
    def viewport(self, viewport: RectLike) -> None: ...
    def reset(self, rectangle: RectLike) -> None: ...
    def move(self, x: float, y: float) -> None: ...
    def rotate(self, angle: float) -> None: ...
    def zoom(self, factor: float) -> None: ...
    @property
    def transform(self) -> Transform: ...
    @property
    def inverse_transform(self) -> Transform: ...


class RenderTarget(Drawable):
    def clear(self, color: Color | None = None) -> None: ...
    @property
    def view(self) -> View: ...
    @view.setter
    def view(self, view: View) -> None: ...
    @property
    def default_view(self) -> View: ...
    def get_viewport(self, view: View) -> Rect: ...
    def map_pixel_to_coords(self, point: Vector2Like, view: View | None = None) -> Vector2: ...
    def map_coords_to_pixel(self, point: Vector2Like, view: View | None = None) -> Vector2: ...
    def draw(self, drawable: Drawable, states: RenderStates | None = None) -> None: ...
    @property
    def size(self) -> Vector2: ...
    @property
    def width(self) -> int | float: ...
    @property
    def height(self) -> int | float: ...
    def push_GL_states(self) -> None: ...
    def pop_GL_states(self) -> None: ...
    def reset_GL_states(self) -> None: ...


class RenderWindow(Window, RenderTarget):
    def __init__(
        self,
        mode: VideoMode,
        title: str,
        style: int = ...,
        settings: ContextSettings = ...,
    ) -> None: ...
    def capture(self) -> Image: ...


class RenderTexture(RenderTarget):
    def __init__(self, width: int, height: int, depthBuffer: bool = False) -> None: ...
    @property
    def smooth(self) -> bool: ...
    @smooth.setter
    def smooth(self, smooth: bool) -> None: ...
    @property
    def repeated(self) -> bool: ...
    @repeated.setter
    def repeated(self, repeated: bool) -> None: ...
    @property
    def active(self) -> NoReturn: ...
    @active.setter
    def active(self, active: bool) -> None: ...
    def display(self) -> None: ...
    @property
    def texture(self) -> Texture: ...


class HandledWindow(RenderTarget):
    def create(self, window_handle: int, settings: ContextSettings | None = None) -> None: ...
    def display(self) -> None: ...
