from __future__ import annotations

from typing import Any, ClassVar, Iterator, TypeAlias, overload

Number: TypeAlias = int | float
Vector2Like: TypeAlias = Vector2 | tuple[Number, Number]
Vector3Like: TypeAlias = Vector3 | tuple[Number, Number, Number]


class Time:
    ZERO: ClassVar[Time]

    def __init__(self) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def seconds(self) -> float: ...
    @seconds.setter
    def seconds(self, seconds: float) -> None: ...
    @property
    def milliseconds(self) -> int: ...
    @milliseconds.setter
    def milliseconds(self, milliseconds: int) -> None: ...
    @property
    def microseconds(self) -> int: ...
    @microseconds.setter
    def microseconds(self, microseconds: int) -> None: ...
    def __add__(self, other: Time) -> Time: ...
    def __sub__(self, other: Time) -> Time: ...
    def __mul__(self, other: Number) -> Time: ...
    def __rmul__(self, other: Number) -> Time: ...
    @overload
    def __truediv__(self, other: Time) -> float: ...
    @overload
    def __truediv__(self, other: Number) -> Time: ...
    def __mod__(self, other: Time) -> Time: ...
    def __iadd__(self, other: Time) -> Time: ...
    def __isub__(self, other: Time) -> Time: ...
    def __imul__(self, other: Number) -> Time: ...
    def __itruediv__(self, other: Number) -> Time: ...
    def __imod__(self, other: Time) -> Time: ...
    def __neg__(self) -> Time: ...
    def __eq__(self, other: object) -> bool: ...
    def __lt__(self, other: Time) -> bool: ...
    def __le__(self, other: Time) -> bool: ...
    def __gt__(self, other: Time) -> bool: ...
    def __ge__(self, other: Time) -> bool: ...


class Clock:
    def __init__(self) -> None: ...
    @property
    def elapsed_time(self) -> Time: ...
    def restart(self) -> Time: ...


class Vector2:
    def __init__(self, x: Number = 0, y: Number = 0) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def x(self) -> Number: ...
    @x.setter
    def x(self, value: Number) -> None: ...
    @property
    def y(self) -> Number: ...
    @y.setter
    def y(self, value: Number) -> None: ...
    def __iter__(self) -> Iterator[Number]: ...
    def __add__(self, other: Vector2Like) -> Vector2: ...
    def __sub__(self, other: Vector2Like) -> Vector2: ...
    def __mul__(self, other: Number) -> Vector2: ...
    def __rmul__(self, other: Number) -> Vector2: ...
    def __truediv__(self, other: Number) -> Vector2: ...
    def __iadd__(self, other: Vector2Like) -> Vector2: ...
    def __isub__(self, other: Vector2Like) -> Vector2: ...
    def __imul__(self, other: Number) -> Vector2: ...
    def __itruediv__(self, other: Number) -> Vector2: ...
    def __neg__(self) -> Vector2: ...
    def __eq__(self, other: object) -> bool: ...


class Vector3:
    def __init__(self, x: Number = 0, y: Number = 0, z: Number = 0) -> None: ...
    def __repr__(self) -> str: ...
    @property
    def x(self) -> Number: ...
    @x.setter
    def x(self, value: Number) -> None: ...
    @property
    def y(self) -> Number: ...
    @y.setter
    def y(self, value: Number) -> None: ...
    @property
    def z(self) -> Number: ...
    @z.setter
    def z(self, value: Number) -> None: ...
    def __iter__(self) -> Iterator[Number]: ...
    def __add__(self, other: Vector3Like) -> Vector3: ...
    def __sub__(self, other: Vector3Like) -> Vector3: ...
    def __mul__(self, other: Number) -> Vector3: ...
    def __rmul__(self, other: Number) -> Vector3: ...
    def __truediv__(self, other: Number) -> Vector3: ...
    def __iadd__(self, other: Vector3Like) -> Vector3: ...
    def __isub__(self, other: Vector3Like) -> Vector3: ...
    def __imul__(self, other: Number) -> Vector3: ...
    def __itruediv__(self, other: Number) -> Vector3: ...
    def __neg__(self) -> Vector3: ...
    def __eq__(self, other: object) -> bool: ...


def sleep(duration: Time) -> None: ...
def seconds(amount: float) -> Time: ...
def milliseconds(amount: int) -> Time: ...
def microseconds(amount: int) -> Time: ...


def __getattr__(name: str) -> Any: ...