from __future__ import annotations

from collections.abc import Generator, Iterable
from enum import IntEnum
from typing import Any, ClassVar, NoReturn

from .system import Vector2, Vector3

Vector2Like = Vector2 | tuple[int | float, int | float]


def __getattr__(name: str) -> Any: ...


class Style:
    NONE: ClassVar[int]
    TITLEBAR: ClassVar[int]
    RESIZE: ClassVar[int]
    CLOSE: ClassVar[int]
    FULLSCREEN: ClassVar[int]
    DEFAULT: ClassVar[int]


class Attribute(IntEnum):
    DEFAULT = 0
    CORE = 1
    DEBUG = 4


class EventType(IntEnum):
    CLOSED = 0
    RESIZED = 1
    LOST_FOCUS = 2
    GAINED_FOCUS = 3
    TEXT_ENTERED = 4
    KEY_PRESSED = 5
    KEY_RELEASED = 6
    MOUSE_WHEEL_MOVED = 7
    MOUSE_WHEEL_SCROLLED = 8
    MOUSE_BUTTON_PRESSED = 9
    MOUSE_BUTTON_RELEASED = 10
    MOUSE_MOVED = 11
    MOUSE_ENTERED = 12
    MOUSE_LEFT = 13
    JOYSTICK_BUTTON_PRESSED = 14
    JOYSTICK_BUTTON_RELEASED = 15
    JOYSTICK_MOVED = 16
    JOYSTICK_CONNECTED = 17
    JOYSTICK_DISCONNECTED = 18
    TOUCH_BEGAN = 19
    TOUCH_MOVED = 20
    TOUCH_ENDED = 21
    SENSOR_CHANGED = 22
    COUNT = 23


class Event:
    @property
    def type(self) -> EventType: ...
    def __contains__(self, key: str) -> bool: ...
    def __getitem__(self, key: str) -> Any: ...
    def get(self, key: str, default: Any = None) -> Any: ...
    def items(self) -> Iterable[tuple[str, Any]]: ...
    def keys(self) -> Iterable[str]: ...
    def values(self) -> Iterable[Any]: ...


class VideoMode:
    def __init__(self, width: int = 0, height: int = 0, bits_per_pixel: int = 32) -> None: ...
    @property
    def width(self) -> int: ...
    @width.setter
    def width(self, width: int) -> None: ...
    @property
    def height(self) -> int: ...
    @height.setter
    def height(self, height: int) -> None: ...
    @property
    def bits_per_pixel(self) -> int: ...
    @bits_per_pixel.setter
    def bits_per_pixel(self, bits_per_pixel: int) -> None: ...
    @classmethod
    def get_desktop_mode(cls) -> VideoMode: ...
    @classmethod
    def get_fullscreen_modes(cls) -> tuple[VideoMode, ...]: ...
    def is_valid(self) -> bool: ...


class ContextSettings:
    def __init__(
        self,
        depth: int = 0,
        stencil: int = 0,
        antialiasing: int = 0,
        major: int = 1,
        minor: int = 1,
        attributes: int = Attribute.DEFAULT,
    ) -> None: ...
    @property
    def depth_bits(self) -> int: ...
    @depth_bits.setter
    def depth_bits(self, depth_bits: int) -> None: ...
    @property
    def stencil_bits(self) -> int: ...
    @stencil_bits.setter
    def stencil_bits(self, stencil_bits: int) -> None: ...
    @property
    def antialiasing_level(self) -> int: ...
    @antialiasing_level.setter
    def antialiasing_level(self, antialiasing_level: int) -> None: ...
    @property
    def major_version(self) -> int: ...
    @major_version.setter
    def major_version(self, major_version: int) -> None: ...
    @property
    def minor_version(self) -> int: ...
    @minor_version.setter
    def minor_version(self, minor_version: int) -> None: ...
    @property
    def attribute_flags(self) -> int: ...
    @attribute_flags.setter
    def attribute_flags(self, attribute_flags: int) -> None: ...


class Window:
    def __init__(
        self,
        mode: VideoMode,
        title: str,
        style: int = ...,
        settings: ContextSettings = ...,
    ) -> None: ...
    def create(
        self,
        mode: VideoMode,
        title: str,
        style: int = ...,
        settings: ContextSettings = ...,
    ) -> None: ...
    def close(self) -> None: ...
    @property
    def is_open(self) -> bool: ...
    @property
    def settings(self) -> ContextSettings: ...
    @property
    def events(self) -> Generator[Event, None, None]: ...
    def poll_event(self) -> Event | None: ...
    def wait_event(self) -> Event | None: ...
    @property
    def position(self) -> Vector2: ...
    @position.setter
    def position(self, position: Vector2Like) -> None: ...
    @property
    def size(self) -> Vector2: ...
    @size.setter
    def size(self, size: Vector2Like) -> None: ...
    @property
    def title(self) -> NoReturn: ...
    @title.setter
    def title(self, title: str) -> None: ...
    def set_icon(self, width: int, height: int, pixels: bytes) -> None: ...
    @property
    def visible(self) -> NoReturn: ...
    @visible.setter
    def visible(self, visible: bool) -> None: ...
    def show(self) -> None: ...
    def hide(self) -> None: ...
    @property
    def vertical_synchronization(self) -> NoReturn: ...
    @vertical_synchronization.setter
    def vertical_synchronization(self, vertical_synchronization: bool) -> None: ...
    @property
    def mouse_cursor_visible(self) -> NoReturn: ...
    @mouse_cursor_visible.setter
    def mouse_cursor_visible(self, mouse_cursor_visible: bool) -> None: ...
    @property
    def key_repeat_enabled(self) -> NoReturn: ...
    @key_repeat_enabled.setter
    def key_repeat_enabled(self, key_repeat_enabled: bool) -> None: ...
    @property
    def framerate_limit(self) -> NoReturn: ...
    @framerate_limit.setter
    def framerate_limit(self, framerate_limit: int) -> None: ...
    @property
    def joystick_threshold(self) -> NoReturn: ...
    @joystick_threshold.setter
    def joystick_threshold(self, joystick_threshold: float) -> None: ...
    @property
    def active(self) -> NoReturn: ...
    @active.setter
    def active(self, active: bool) -> None: ...
    def request_focus(self) -> None: ...
    def has_focus(self) -> bool: ...
    def display(self) -> None: ...
    @property
    def system_handle(self) -> int: ...
    def on_create(self) -> None: ...
    def on_resize(self) -> None: ...


class Key(IntEnum):
    UNKNOWN = 0


class Keyboard:
    @staticmethod
    def is_key_pressed(key: int) -> bool: ...
    @staticmethod
    def set_virtual_keyboard_visible(visible: bool) -> None: ...
    def __getattr__(self, name: str) -> Any: ...


class Axis(IntEnum):
    X = 0


class Joystick:
    COUNT: ClassVar[int]
    BUTTON_COUNT: ClassVar[int]
    AXIS_COUNT: ClassVar[int]

    @staticmethod
    def is_connected(joystick: int) -> bool: ...
    @staticmethod
    def get_button_count(joystick: int) -> int: ...
    @staticmethod
    def has_axis(joystick: int, axis: int) -> bool: ...
    @staticmethod
    def is_button_pressed(joystick: int, button: int) -> bool: ...
    @staticmethod
    def get_axis_position(joystick: int, axis: int) -> float: ...
    @staticmethod
    def get_identification(joystick: int) -> tuple[str, int, int]: ...
    @staticmethod
    def update() -> None: ...


class Button(IntEnum):
    LEFT = 0
    RIGHT = 1
    MIDDLE = 2


class Wheel(IntEnum):
    VERTICAL_WHEEL = 0
    HORIZONTAL_WHEEL = 1


class Mouse:
    @staticmethod
    def is_button_pressed(button: int) -> bool: ...
    @staticmethod
    def get_position(window: Window | None = None) -> Vector2: ...
    @staticmethod
    def set_position(position: Vector2Like, window: Window | None = None) -> None: ...


class Touch:
    @staticmethod
    def is_down(finger: int) -> bool: ...
    @staticmethod
    def get_position(finger: int, window: Window | None = None) -> Vector2: ...


class Type(IntEnum):
    ACCELEROMETER = 0


class Sensor:
    @staticmethod
    def is_available(sensor: int) -> bool: ...
    @staticmethod
    def set_enabled(sensor: int, enabled: bool) -> None: ...
    @staticmethod
    def get_value(sensor: int) -> Vector3: ...


class Context:
    @property
    def active(self) -> NoReturn: ...
    @active.setter
    def active(self, active: bool) -> None: ...
